language: node_js
sudo: false
node_js:
- 4
- 6
- stable
script:
- npm test

cache:
  directories:
    - node_modules

before_script:
  - npm run linter

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
